# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/protos/snapshot.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pb/protos/snapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pkg.lib.pb.model.protos import models_pb2 as pkg_dot_lib_dot_pb_dot_model_dot_protos_dot_models__pb2
from pb.protos import changes_pb2 as pb_dot_protos_dot_changes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pb/protos/snapshot.proto\x12\x07\x61nytype\x1a$pkg/lib/pb/model/protos/models.proto\x1a\x17pb/protos/changes.proto\"m\n\x10SnapshotWithType\x12-\n\x06sbType\x18\x01 \x01(\x0e\x32\x1d.anytype.model.SmartBlockType\x12*\n\x08snapshot\x18\x02 \x01(\x0b\x32\x18.anytype.Change.Snapshot\"\xb7\x01\n\x07Profile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x18\n\x10spaceDashboardId\x18\x05 \x01(\t\x12\x11\n\tprofileId\x18\x06 \x01(\t\x12\x13\n\x0b\x61nalyticsId\x18\x07 \x01(\t\x12\x14\n\x0cstartingPage\x18\x08 \x01(\t\x12%\n\x07widgets\x18\t \x03(\x0b\x32\x14.anytype.WidgetBlock\"v\n\x0bWidgetBlock\x12:\n\x06layout\x18\x01 \x01(\x0e\x32*.anytype.model.Block.Content.Widget.Layout\x12\x16\n\x0etargetObjectId\x18\x02 \x01(\t\x12\x13\n\x0bobjectLimit\x18\x03 \x01(\x05\x42\x04Z\x02pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.protos.snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002pb'
  _globals['_SNAPSHOTWITHTYPE']._serialized_start=100
  _globals['_SNAPSHOTWITHTYPE']._serialized_end=209
  _globals['_PROFILE']._serialized_start=212
  _globals['_PROFILE']._serialized_end=395
  _globals['_WIDGETBLOCK']._serialized_start=397
  _globals['_WIDGETBLOCK']._serialized_end=515
# @@protoc_insertion_point(module_scope)
